## **Task 4: Analyze data**

<hr/>

In [1]:
# Import libraries
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
import pandas as pd
from tqdm import tqdm
from sklearn.feature_extraction.text import CountVectorizer

### *1. Read preprocessing data from mongoDB Local*

In [2]:
client_Tlocal = MongoClient('mongodb://localhost:27017/')
db_Tlocal = client_Tlocal ['Task2_Database']
collection_Tlocal = db_Tlocal['Shopee_Full_Preprocessing_Data']
num_documents_Tlocal = collection_Tlocal.count_documents({})
print("Number of documents in the collection:", num_documents_Tlocal)

Number of documents in the collection: 549791

In [3]:
# Read preprocessing data from Thinh's MongoDB Local
def read_preprocessing_data(collection, num_documents):
    data_list = []
    total_documents = num_documents
    with tqdm(total=total_documents, desc='Getting Documents') as pbar:
        for document in collection.find({"crawl_id": {"$gte": 0, "$lt": total_documents}}):
            del document['_id']
            data_list.append(document)
            pbar.update(1)    

    df = pd.DataFrame(data_list)
    return df

In [4]:
df = read_preprocessing_data(collection_Tlocal, num_documents_Tlocal)

Getting Documents: 100%|██████████| 549791/549791 [01:46<00:00, 5183.76it/s]

In [5]:
df

,itemid,shopid,name,stock,sold,historical_sold,liked_count,cmt_count,item_status,price,...,global_sold_count,flash_sale_stock,crawl_time,crawl_id,color,size,rating_star,rating_count,rcount_with_image,rcount_with_context
0,19393753758,40342563,"Bộ Đồ Nam AVIANO 4 Màu Dài Tay, Bộ Thể Thao Na...",159,161,163,41,40,normal,285000.0,...,163,159,2023-11-02 12:00:00,0,"ĐEN, TIÊU","[M, L, XL, XXL]",4.925000,"[40, 0, 0, 0, 3, 37]",16,21
1,4263018116,40342563,Bộ Thể Thao Nam Chất Nỉ 4 Màu Trẻ Trung Năng Đ...,240,3098,39098,5112,12119,normal,185000.0,...,39098,240,2023-11-02 12:00:00,1,Ghi,"[M, L, XL, XXL]",4.845551,"[12120, 119, 86, 265, 616, 11034]",5409,6928
2,18484638101,40342563,"Bộ Đồ Nam AVIANO 4 Màu Dài Tay, Bộ Thể Thao Na...",222,439,462,77,136,normal,185000.0,...,462,222,2023-11-02 12:00:00,2,"ĐEN, TRẮNG","[M, L, XL, XXL]",4.897059,"[136, 2, 1, 0, 3, 130]",58,74
3,23081308025,40342563,"Áo Khoác Nam AVIANO Cao Cấp Chống Nước,Chống G...",216,387,397,107,118,normal,229000.0,...,397,216,2023-11-02 12:00:00,3,ĐEN,"[M, L, XL, XXL]",4.872881,"[118, 1, 2, 1, 3, 111]",45,59
4,18040585153,40342563,Bộ Quần Áo Cho Bé Thiết Kế Kẻ Ô Cao Cấp Thời T...,317,26,227,35,87,normal,99000.0,...,227,0,2023-11-02 12:00:00,4,Nâu,"[2, 3, 4, 5, 6]",4.875000,"[88, 1, 0, 2, 3, 82]",45,51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549786,1258757931,75123404,Vớ Cổ Trung Dành Cho Trẻ Em 12-14 Tuổi Thương ...,70,0,3,0,1,normal,21000.0,...,3,0,2023-12-05 23:20:53,549786,XANH,[No size],5.000000,"[1, 0, 0, 0, 0, 1]",0,0
549787,1258817062,75123404,Vớ Trẻ Em Cổ Trung 3-5 Tuổi EBK170,75,0,14,1,1,normal,25000.0,...,14,0,2023-12-05 23:20:53,549787,XANH,[No size],5.000000,"[1, 0, 0, 0, 0, 1]",0,0
549788,1267439667,75123404,Vớ Không Cổ Dành Cho Nam Thương Hiệu ELLE EH L...,60,0,22,2,1,normal,50000.0,...,22,0,2023-12-05 23:20:53,549788,ĐEN,[No size],5.000000,"[1, 0, 0, 0, 0, 1]",0,1
549789,1267555891,75123404,Vớ Thể Thao Cổ Trung Dệt Xù Dành Cho Nam Thươn...,79,0,11,4,4,normal,70000.0,...,11,0,2023-12-05 23:20:53,549789,"ĐEN, XÁM",[No size],5.000000,"[4, 0, 0, 0, 0, 4]",0,2
549790,1267589839,75123404,Vớ Thể Thao Cổ Ngắn Dệt Xù Dành Cho Nam Thương...,20,0,35,3,8,normal,70000.0,...,35,0,2023-12-05 23:20:53,549790,ĐEN,[No size],5.000000,"[8, 0, 0, 0, 0, 8]",1,1

### *2. Read raw data from mongoDB Atlas*

In [6]:
# MONGODB_URI = "mongodb+srv://MasterMind:MasterMind@productpage.nj9srv4.mongodb.net/"
# client_SAtlas = MongoClient(MONGODB_URI, server_api=ServerApi('1'))

# # Send a ping to confirm a successful connection
# try:
#     client_SAtlas.admin.command('ping')
#     print("Pinged your deployment. You successfully connected to MongoDB!")
# except Exception as e:
#     print(e)
# db_SAtlas = client_SAtlas.get_database('product_pages')
# records = db_SAtlas.items

#### *2.1. Preprocessing data in Son MongoDB Atlas*

In [7]:
# cursor = records.find({})

In [8]:
# data_list = []
# for document in cursor:
#             del document['_id']
#             data_list.append(document)
            
# raw_df = pd.DataFrame(data_list)

In [9]:
# json_content = pd.DataFrame(raw_df['items'].apply(pd.Series))
# item_infor = pd.DataFrame(json_content['item'].apply(pd.Series))
# description_df = pd.DataFrame(item_infor[['item_id','shop_id', 'title', 'description']])
# description_df.to_csv('sample.csv',index=False,header=True,encoding="utf-8-sig")

### *3. Analyze keyword from title of products*

In [10]:
raw_df = df.copy()
raw_df

,itemid,shopid,name,stock,sold,historical_sold,liked_count,cmt_count,item_status,price,...,global_sold_count,flash_sale_stock,crawl_time,crawl_id,color,size,rating_star,rating_count,rcount_with_image,rcount_with_context
0,19393753758,40342563,"Bộ Đồ Nam AVIANO 4 Màu Dài Tay, Bộ Thể Thao Na...",159,161,163,41,40,normal,285000.0,...,163,159,2023-11-02 12:00:00,0,"ĐEN, TIÊU","[M, L, XL, XXL]",4.925000,"[40, 0, 0, 0, 3, 37]",16,21
1,4263018116,40342563,Bộ Thể Thao Nam Chất Nỉ 4 Màu Trẻ Trung Năng Đ...,240,3098,39098,5112,12119,normal,185000.0,...,39098,240,2023-11-02 12:00:00,1,Ghi,"[M, L, XL, XXL]",4.845551,"[12120, 119, 86, 265, 616, 11034]",5409,6928
2,18484638101,40342563,"Bộ Đồ Nam AVIANO 4 Màu Dài Tay, Bộ Thể Thao Na...",222,439,462,77,136,normal,185000.0,...,462,222,2023-11-02 12:00:00,2,"ĐEN, TRẮNG","[M, L, XL, XXL]",4.897059,"[136, 2, 1, 0, 3, 130]",58,74
3,23081308025,40342563,"Áo Khoác Nam AVIANO Cao Cấp Chống Nước,Chống G...",216,387,397,107,118,normal,229000.0,...,397,216,2023-11-02 12:00:00,3,ĐEN,"[M, L, XL, XXL]",4.872881,"[118, 1, 2, 1, 3, 111]",45,59
4,18040585153,40342563,Bộ Quần Áo Cho Bé Thiết Kế Kẻ Ô Cao Cấp Thời T...,317,26,227,35,87,normal,99000.0,...,227,0,2023-11-02 12:00:00,4,Nâu,"[2, 3, 4, 5, 6]",4.875000,"[88, 1, 0, 2, 3, 82]",45,51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549786,1258757931,75123404,Vớ Cổ Trung Dành Cho Trẻ Em 12-14 Tuổi Thương ...,70,0,3,0,1,normal,21000.0,...,3,0,2023-12-05 23:20:53,549786,XANH,[No size],5.000000,"[1, 0, 0, 0, 0, 1]",0,0
549787,1258817062,75123404,Vớ Trẻ Em Cổ Trung 3-5 Tuổi EBK170,75,0,14,1,1,normal,25000.0,...,14,0,2023-12-05 23:20:53,549787,XANH,[No size],5.000000,"[1, 0, 0, 0, 0, 1]",0,0
549788,1267439667,75123404,Vớ Không Cổ Dành Cho Nam Thương Hiệu ELLE EH L...,60,0,22,2,1,normal,50000.0,...,22,0,2023-12-05 23:20:53,549788,ĐEN,[No size],5.000000,"[1, 0, 0, 0, 0, 1]",0,1
549789,1267555891,75123404,Vớ Thể Thao Cổ Trung Dệt Xù Dành Cho Nam Thươn...,79,0,11,4,4,normal,70000.0,...,11,0,2023-12-05 23:20:53,549789,"ĐEN, XÁM",[No size],5.000000,"[4, 0, 0, 0, 0, 4]",0,2
549790,1267589839,75123404,Vớ Thể Thao Cổ Ngắn Dệt Xù Dành Cho Nam Thương...,20,0,35,3,8,normal,70000.0,...,35,0,2023-12-05 23:20:53,549790,ĐEN,[No size],5.000000,"[8, 0, 0, 0, 0, 8]",1,1

#### 3.1. Filtering top 50 products from top shop mall and normal shop:

In [11]:
top_shopee_mall_id = [40342563, 225909574, 68613764, 24710134, 127217331, 60297616, 111639450,\
                      317477677, 201774917, 59596762, 168678363, 92937520, 68988783, 263713672,\
                      38038824, 277366270, 70677296, 1620236, 17893078, 31522834, 16649961,\
                      296132807, 257412160]
normal_shop_id = [999122826, 952153869, 47401874, 80968732,744060250,127049276,324062232,205125399,\
                  427693365, 360972139, 168195778, 913496573, 299977840, 183199642, 416018485,\
                  264542552, 78461361, 329002439, 108136164, 75123404]

In [12]:
raw_df = raw_df[['itemid','shopid','name','sold','price','rating_star']]
raw_df

,itemid,shopid,name,sold,price,rating_star
0,19393753758,40342563,"Bộ Đồ Nam AVIANO 4 Màu Dài Tay, Bộ Thể Thao Na...",161,285000.0,4.925000
1,4263018116,40342563,Bộ Thể Thao Nam Chất Nỉ 4 Màu Trẻ Trung Năng Đ...,3098,185000.0,4.845551
2,18484638101,40342563,"Bộ Đồ Nam AVIANO 4 Màu Dài Tay, Bộ Thể Thao Na...",439,185000.0,4.897059
3,23081308025,40342563,"Áo Khoác Nam AVIANO Cao Cấp Chống Nước,Chống G...",387,229000.0,4.872881
4,18040585153,40342563,Bộ Quần Áo Cho Bé Thiết Kế Kẻ Ô Cao Cấp Thời T...,26,99000.0,4.875000
...,...,...,...,...,...,...
549786,1258757931,75123404,Vớ Cổ Trung Dành Cho Trẻ Em 12-14 Tuổi Thương ...,0,21000.0,5.000000
549787,1258817062,75123404,Vớ Trẻ Em Cổ Trung 3-5 Tuổi EBK170,0,25000.0,5.000000
549788,1267439667,75123404,Vớ Không Cổ Dành Cho Nam Thương Hiệu ELLE EH L...,0,50000.0,5.000000
549789,1267555891,75123404,Vớ Thể Thao Cổ Trung Dệt Xù Dành Cho Nam Thươn...,0,70000.0,5.000000
549790,1267589839,75123404,Vớ Thể Thao Cổ Ngắn Dệt Xù Dành Cho Nam Thương...,0,70000.0,5.000000

In [13]:
# Remove duplicated data and keep the last value
analyzed_df = raw_df.drop_duplicates(subset='itemid', keep='last')
analyzed_df.reset_index(drop=True, inplace=True)
analyzed_df

,itemid,shopid,name,sold,price,rating_star
0,16985661061,317477677,Quần Jean LEVENTS Crayon/ Blue,5,413000.0,4.962264
1,6944158731,92937520,Áo sơ mi dài tay nam Owen Regularfit- AR20728DT,45,598000.0,4.881356
2,15494176620,92937520,OWEN - Quần Boxer nam màu Xanh - QLBR221094,1,120000.0,0.000000
3,14498861181,92937520,OWEN - Áo sơ mi Nam dài tay Slim Fit màu Navy ...,0,1200000.0,0.000000
4,23680547799,296132807,Quần Đùi Nam SAIGONESE Short Thun Phối Line Th...,4,119000.0,5.000000
...,...,...,...,...,...,...
9307,1258757931,75123404,Vớ Cổ Trung Dành Cho Trẻ Em 12-14 Tuổi Thương ...,0,21000.0,5.000000
9308,1258817062,75123404,Vớ Trẻ Em Cổ Trung 3-5 Tuổi EBK170,0,25000.0,5.000000
9309,1267439667,75123404,Vớ Không Cổ Dành Cho Nam Thương Hiệu ELLE EH L...,0,50000.0,5.000000
9310,1267555891,75123404,Vớ Thể Thao Cổ Trung Dệt Xù Dành Cho Nam Thươn...,0,70000.0,5.000000
9311,1267589839,75123404,Vớ Thể Thao Cổ Ngắn Dệt Xù Dành Cho Nam Thương...,0,70000.0,5.000000

In [14]:
# SM: Shop Mall
# NM: Normal Shop
top_50_items_SM_df = pd.DataFrame(columns=['shopid','name'])
top_50_items_NM_df = pd.DataFrame(columns=['shopid','name'])

In [15]:
# Get 50 products from each Shop Mall (SM)
for i in tqdm(range(0,len(top_shopee_mall_id))):
    shopid = top_shopee_mall_id[i]
    all_items = analyzed_df[analyzed_df['shopid'] == str(shopid)][['name','sold']].sort_values(by='sold',ascending=False)
    try:
        top_50_SM_items = list(all_items['name'].iloc[:50])
    except:
        top_50_SM_items = list(all_items['name'])
    shopid_list = [shopid] * len(top_50_SM_items)
    result = pd.DataFrame({'shopid': shopid_list, 'name': top_50_SM_items})
    top_50_items_SM_df = pd.concat([top_50_items_SM_df, result], ignore_index=True)

 26%|██▌       | 6/23 [00:00<00:00, 59.41it/s]

100%|██████████| 23/23 [00:00<00:00, 63.36it/s]

In [16]:
top_50_items_SM_df

         shopid                                               name
0      40342563  Bộ Thể Thao Nam Chất Nỉ 4 Màu Trẻ Trung Năng Đ...
1      40342563  Bộ Đồ Nam AVIANO 4 Màu Dài Tay, Bộ Thể Thao Na...
2      40342563        COMBO 5 đôi tất nam Trơn VICERO Kháng khuẩn
3      40342563  Áo Nỉ Nam Thời Trang Trẻ Trung Chất Vải Co Dãn...
4      40342563  Bộ Thể Thao Nam 3 Sọc Mùa Đông Da Cá Chéo Thời...
...         ...                                                ...
1133  257412160  Áo thun nam cổ tròn, T-shirt nam đen in AREMI,...
1134  257412160  Áo polo nam tay ngắn cổ trụ AREMI thiết kế độc...
1135  257412160  Áo thun nam tay ngắn cổ tròn thiết kế AREMI ch...
1136  257412160  Áo polo nam cổ trụ tay ngắn AREMI thiết kế đơn...
1137  257412160  Áo polo nam tay ngắn cổ trụ thiết kế AREMI chấ...

[1138 rows x 2 columns]

In [17]:
# Get 50 products from each Normal Shop (NM)
for i in tqdm(range(0,len(normal_shop_id))):
    shopid = normal_shop_id[i]
    all_items = analyzed_df[analyzed_df['shopid'] == str(shopid)][['name','sold']].sort_values(by='sold',ascending=False)
    try:
        top_50_NM_items = list(all_items['name'].iloc[:50])
    except:
        top_50_NM_items = list(all_items['name'])
    shopid_list = [shopid] * len(top_50_NM_items)
    result = pd.DataFrame({'shopid': shopid_list, 'name': top_50_NM_items})
    top_50_items_NM_df = pd.concat([top_50_items_NM_df, result], ignore_index=True)

 75%|███████▌  | 15/20 [00:00<00:00, 73.51it/s]

100%|██████████| 20/20 [00:00<00:00, 63.70it/s]

In [18]:
top_50_items_NM_df

        shopid                                               name
0    999122826  Hàng Có Sẵn! Hàng Có Sẵn!Phong cách dân tộc mù...
1    999122826  Hàng Có Sẵn! Hàng Có Sẵn!Shaoye Quần Váy Dài D...
2    999122826  Hàng sẵn sàng!Nam giới kích thước lớn phong cá...
3    999122826  Hàng Có Sẵn!Quần Giả Váy Lưng Thun Ống Rộng Th...
4    999122826  Hàng Có Sẵn!Set Đồ Thể Thao Phối Áo Ba Lỗ Vải ...
..         ...                                                ...
905   75123404  Vớ Thể Thao Cổ Trung Dành Cho Nam Thương Hiệu ...
906   75123404  Vớ Trẻ Em Cổ Ngắn 2-3 Tuổi Thương Hiệu ELLE EB...
907   75123404  Set 4 Đôi Vớ Công Sở Cổ Trung Dành Cho Nam Thư...
908   75123404  Vớ Công Sở Cổ Trung Dành Cho Nam Thương Hiệu E...
909   75123404  Vớ Không Cổ Dành Cho Nam Thương Hiệu ELLE EH L...

[910 rows x 2 columns]

#### 3.2. Tokenize k-word in each products:

In [19]:
def tokenize_k_word(documents, k, stopwords):
    preprocessed_documents = [doc.lower() for doc in documents]
    vectorizer = CountVectorizer(ngram_range= (k,k), stop_words= stopwords)
    word_counts = vectorizer.fit_transform(preprocessed_documents)
    words = vectorizer.get_feature_names_out()
    word_occurrences = word_counts.toarray().sum(axis=0)
    word_count_dict = dict(zip(words, word_occurrences))
    Word = []
    Count = []
    for word, count in word_count_dict.items():
        Word.append(word)
        Count.append(count)
    return Word, Count

#### TOP SHOP MALL

##### **k = 1**

In [20]:
documents = list(top_50_items_SM_df['name'])
stopwords = ['nam', 'áo', 'quần', 'vải']
# stopwords = None
Word, Count = tokenize_k_word(documents, 1, stopwords)
infor_1w_df = pd.DataFrame({'Word': Word, 'Count': Count})
infor_best_1w_df = infor_1w_df.sort_values(by='Count',ascending=False)[:50]
infor_best_1w_df.reset_index(drop=True, inplace=True)
infor_best_1w_df

      Word  Count
0      tay    294
1     chất    278
2       cổ    263
3     thun    236
4      màu    216
5   cotton    206
6       co    205
7     form    184
8      cao    179
9     thao    178
10     thể    176
11    polo    175
12     cấp    169
13    giãn    166
14     dài    163
15  thoáng    153
16   trang    141
17    thời    137
18    ngắn    129
19    dáng    128
20    phối    123
21     mát    118
22     mềm    116
23   trung    116
24      nữ    116
25     trẻ    115
26   chống    114
27   basic    114
28      mi    111
29      sơ    111
30  unisex    111
31   khoác    110
32    lịch    106
33      cá    103
34     hàn    101
35      nỉ     96
36    cách     96
37   trọng     95
38    sang     95
39    quốc     94
40    liệu     93
41    rộng     93
42     gió     90
43      kế     89
44   thiết     89
45     len     86
46   phong     85
47     sấu     84
48      bộ     83
49    trơn     81

Ban đầu, khi chạy dòng lệnh trên thì nhóm em thấy có rất nhiều từ mang tính thời trang (Tức là những từ gần như là phải có trong mọi sản phẩm), thông tin này không hề có giá trị nên nhóm em đã đưa nó vào nhóm stopwords, tức là những từ ngữ không ý nghĩa

##### **k = 2**

In [21]:
# documents = list(top_50_items_SM_df['name'])
documents = list(analyzed_df['name'])
# stopwords = ['nam', 'áo', 'quần', 'vải']
stopwords = None
Word, Count = tokenize_k_word(documents, 2, stopwords)
infor_2w_df = pd.DataFrame({'Word': Word, 'Count': Count})
infor_best_2w_df = infor_2w_df.sort_values(by='Count',ascending=False)[:50]
infor_best_2w_df.reset_index(drop=True, inplace=True)
infor_best_2w_df

             Word  Count
0      thời trang   2149
1           sơ mi   1560
2           áo sơ   1520
3         cao cấp   1427
4          có sẵn   1186
5         hàng có   1185
6      phong cách   1096
7         áo thun   1085
8         cho nam   1085
9        áo khoác    924
10       thể thao    807
11         mi nam    798
12       hàn quốc    790
13        dài tay    725
14        co giãn    704
15         mùa hè    683
16      chất liệu    661
17       ngắn tay    654
18      trang mùa    627
19     quần short    611
20        áo polo    557
21       họa tiết    544
22       tay ngắn    541
23    thương hiệu    540
24         24 giờ    511
25        ảnh 100    479
26       hình ảnh    479
27     chuẩn hình    476
28      cấp chuẩn    473
29        owen áo    459
30         qc cao    458
31        hàng qc    455
32      trẻ trung    448
33     bản supper    432
34        cổ tròn    430
35       sẵn hàng    428
36    supper hàng    426
37       dành cho    400
38     thoáng mát    387
39        nam tay    376
40         mi dài    356
41       sẵn quần    349
42       nam owen    349
43       thiết kế    342
44       thun nam    341
45       polo nam    338
46       màu xanh    335
47        fit màu    326
48  hiệu coolmate    322
49        dày dặn    322

In [22]:
documents = list(top_50_items_SM_df['name'])
# stopwords = ['nam', 'áo', 'quần', 'vải']
stopwords = None
Word, Count = tokenize_k_word(documents, 3, stopwords)
infor_3w_df = pd.DataFrame({'Word': Word, 'Count': Count})
infor_best_3w_df = infor_3w_df.sort_values(by='Count',ascending=False)[:50]
infor_best_3w_df.reset_index(drop=True, inplace=True)
infor_best_3w_df

                    Word  Count
0            áo polo nam    110
1               áo sơ mi    106
2           thể thao nam     80
3            áo thun nam     72
4          cá sấu cotton     48
5             vải cá sấu     45
6              sơ mi nam     44
7        lịch sang trọng     40
8     thời trang everest     40
9        thanh lịch sang     40
10        nam tính thanh     39
11       tính thanh lịch     39
12         thoáng mát co     36
13             sơ mi dài     35
14           mát co giãn     35
15            mi dài tay     35
16  thương hiệu coolmate     35
17           nam cổ tròn     34
18  sang trọng polomanor     34
19          áo khoác gió     33
20       áo thun levents     31
21           áo thể thao     30
22           dài tay nam     30
23      thao nam tsimple     29
24          áo khoác nam     28
25             nam da bò     28
26        giãn thoải mái     28
27        thời trang hàn     28
28         co giãn thoải     28
29        trang hàn quốc     28
30       aremi chất liệu     26
31           nam dài tay     26
32          nam tay ngắn     26
33            áo len nam     25
34         cách hàn quốc     25
35        phong cách hàn     25
36      chất liệu cotton     25
37         co giản chiều     24
38          quần đùi nam     24
39          quần lót nam     24
40             nam có cổ     24
41         unisex nam nữ     23
42        nam 5s fashion     23
43           thấm mồ hôi     23
44         vải thun lạnh     23
45           tập gym vải     23
46        quần short nam     22
47            bộ quần áo     22
48             ví nam da     22
49          nam thể thao     22

# ...

#### NORMAL SHOP

In [23]:
documents = list(top_50_items_NM_df['name'])
# stopwords = ['nam', 'áo', 'quần', 'vải']
stopwords = None
Word, Count = tokenize_k_word(documents, 1, stopwords)
infor_1w_df = pd.DataFrame({'Word': Word, 'Count': Count})
infor_best_1w_df = infor_1w_df.sort_values(by='Count',ascending=False)[:50]
infor_best_1w_df.reset_index(drop=True, inplace=True)
infor_best_1w_df

      Word  Count
0      nam    875
1       áo    486
2     quần    403
3      cao    271
4      cấp    243
5      màu    203
6      vải    196
7     chất    194
8       cổ    185
9      tay    181
10    thun    171
11    hàng    170
12   trang    153
13    thời    150
14     cho    141
15     đẹp    120
16    giày    118
17      co    115
18   khoác    111
19   phong    110
20    cách    108
21     dài    107
22      sơ    106
23      mi    105
24     thể    102
25      bộ    101
26    giãn    101
27      có    101
28    thao    101
29     mùa     98
30  thoáng     94
31     mát     93
32    dáng     92
33     lót     92
34     sịp     92
35     hàn     88
36    lạnh     88
37     đùi     86
38      da     86
39    quốc     84
40   trung     82
41    ngắn     79
42      hè     79
43      mã     73
44      nữ     72
45    hình     71
46     mẫu     71
47   chiều     70
48     trẻ     70
49   chuẩn     69

In [24]:
documents = list(top_50_items_NM_df['name'])
# stopwords = ['nam', 'áo', 'quần', 'vải']
stopwords = None
Word, Count = tokenize_k_word(documents, 2, stopwords)
infor_2w_df = pd.DataFrame({'Word': Word, 'Count': Count})
infor_best_2w_df = infor_2w_df.sort_values(by='Count',ascending=False)[:50]
infor_best_2w_df.reset_index(drop=True, inplace=True)
infor_best_2w_df

           Word  Count
0       cao cấp    241
1    thời trang    150
2      áo khoác    110
3    phong cách    108
4         sơ mi    105
5         áo sơ    103
6      thể thao    101
7       co giãn    101
8       cho nam     89
9      chất vải     84
10    thun lạnh     81
11       mi nam     78
12     hàn quốc     78
13      áo thun     77
14      đùi nam     73
15       mùa hè     72
16     vải thun     70
17   thoáng mát     68
18     nam quần     68
19     dành cho     68
20     quần sịp     61
21  thương hiệu     61
22       nam cổ     61
23   giãn chiều     60
24       có sẵn     58
25      hàng có     58
26     quần lót     57
27     thấm hút     54
28     thun nam     52
29   chuẩn hình     51
30    hiệu elle     50
31      ảnh 100     50
32      dài tay     50
33    trẻ trung     50
34     hình ảnh     50
35    cấp chuẩn     49
36      cổ tròn     47
37   bản supper     47
38        cổ bẻ     47
39       hút mồ     47
40       mồ hôi     46
41      hàng qc     46
42   quần short     46
43      sịp đùi     45
44    chất liệu     44
45       qc cao     44
46  supper hàng     44
47      nam cao     43
48     thao nam     42
49      lạnh co     40

### 3.3 Form dataframe top popular keyword

In [25]:
infor_best_2w_df.head()

         Word  Count
0     cao cấp    241
1  thời trang    150
2    áo khoác    110
3  phong cách    108
4       sơ mi    105

In [26]:
analyzed_df

,itemid,shopid,name,sold,price,rating_star
0,16985661061,317477677,Quần Jean LEVENTS Crayon/ Blue,5,413000.0,4.962264
1,6944158731,92937520,Áo sơ mi dài tay nam Owen Regularfit- AR20728DT,45,598000.0,4.881356
2,15494176620,92937520,OWEN - Quần Boxer nam màu Xanh - QLBR221094,1,120000.0,0.000000
3,14498861181,92937520,OWEN - Áo sơ mi Nam dài tay Slim Fit màu Navy ...,0,1200000.0,0.000000
4,23680547799,296132807,Quần Đùi Nam SAIGONESE Short Thun Phối Line Th...,4,119000.0,5.000000
...,...,...,...,...,...,...
9307,1258757931,75123404,Vớ Cổ Trung Dành Cho Trẻ Em 12-14 Tuổi Thương ...,0,21000.0,5.000000
9308,1258817062,75123404,Vớ Trẻ Em Cổ Trung 3-5 Tuổi EBK170,0,25000.0,5.000000
9309,1267439667,75123404,Vớ Không Cổ Dành Cho Nam Thương Hiệu ELLE EH L...,0,50000.0,5.000000
9310,1267555891,75123404,Vớ Thể Thao Cổ Trung Dệt Xù Dành Cho Nam Thươn...,0,70000.0,5.000000
9311,1267589839,75123404,Vớ Thể Thao Cổ Ngắn Dệt Xù Dành Cho Nam Thương...,0,70000.0,5.000000

In [27]:
analyzed_df['approximate_revenue'] = analyzed_df['sold'] * analyzed_df['price']
analyzed_df

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_1160\3767181646.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  analyzed_df['approximate_revenue'] = analyzed_df['sold'] * analyzed_df['price']

,itemid,shopid,name,sold,price,rating_star,approximate_revenue
0,16985661061,317477677,Quần Jean LEVENTS Crayon/ Blue,5,413000.0,4.962264,2065000.0
1,6944158731,92937520,Áo sơ mi dài tay nam Owen Regularfit- AR20728DT,45,598000.0,4.881356,26910000.0
2,15494176620,92937520,OWEN - Quần Boxer nam màu Xanh - QLBR221094,1,120000.0,0.000000,120000.0
3,14498861181,92937520,OWEN - Áo sơ mi Nam dài tay Slim Fit màu Navy ...,0,1200000.0,0.000000,0.0
4,23680547799,296132807,Quần Đùi Nam SAIGONESE Short Thun Phối Line Th...,4,119000.0,5.000000,476000.0
...,...,...,...,...,...,...,...
9307,1258757931,75123404,Vớ Cổ Trung Dành Cho Trẻ Em 12-14 Tuổi Thương ...,0,21000.0,5.000000,0.0
9308,1258817062,75123404,Vớ Trẻ Em Cổ Trung 3-5 Tuổi EBK170,0,25000.0,5.000000,0.0
9309,1267439667,75123404,Vớ Không Cổ Dành Cho Nam Thương Hiệu ELLE EH L...,0,50000.0,5.000000,0.0
9310,1267555891,75123404,Vớ Thể Thao Cổ Trung Dệt Xù Dành Cho Nam Thươn...,0,70000.0,5.000000,0.0
9311,1267589839,75123404,Vớ Thể Thao Cổ Ngắn Dệt Xù Dành Cho Nam Thương...,0,70000.0,5.000000,0.0

In [28]:
test_df = analyzed_df[analyzed_df['shopid'] == '40342563']
search_string = 'cao cấp'
# Hiển thị các hàng có chứa chuỗi cụ thể
t = test_df.sort_values(by='sold',ascending=False).reset_index(drop=True)
t.reset_index(inplace=True)
t

,index,itemid,shopid,name,sold,price,rating_star,approximate_revenue
0,0,4263018116,40342563,Bộ Thể Thao Nam Chất Nỉ 4 Màu Trẻ Trung Năng Đ...,6595,185000.0,4.846812,1.220075e+09
1,1,18484638101,40342563,"Bộ Đồ Nam AVIANO 4 Màu Dài Tay, Bộ Thể Thao Na...",3912,195000.0,4.847720,7.628400e+08
2,2,1679232406,40342563,COMBO 5 đôi tất nam Trơn VICERO Kháng khuẩn,2731,60000.0,4.791030,1.638600e+08
3,3,4649597158,40342563,Áo Nỉ Nam Thời Trang Trẻ Trung Chất Vải Co Dãn...,2704,129000.0,4.882612,3.488160e+08
4,4,19749576955,40342563,Bộ Thể Thao Nam 3 Sọc Mùa Đông Da Cá Chéo Thời...,1833,275000.0,4.874379,5.040750e+08
...,...,...,...,...,...,...,...,...
186,186,16425906633,40342563,Áo Polo AVIANO Tay Ngắn 2 Màu Xanh Trắng Bo Cổ...,0,139000.0,4.910995,0.000000e+00
187,187,13681855901,40342563,Áo Polo Ngắn Tay 5 Màu Thời Trang Cao Cấp Thiế...,0,99000.0,4.979522,0.000000e+00
188,188,18588438649,40342563,Áo Polo Nam AVIANO Chất Liệu Co Giãn Thấm Hút ...,0,139000.0,5.000000,0.000000e+00
189,189,12073629517,40342563,"Bộ Đồ Nam AVIANO, Set Đồ Nam Polo Tay Ngắn Mix...",0,199000.0,4.924906,0.000000e+00
190,190,22630455837,40342563,"Bộ Quần Áo Nam Mùa Hè AVIANO, Bộ Đồ Nam Cộc Ta...",0,169000.0,4.857143,0.000000e+00

In [29]:
normal_shop_id

[999122826,
 952153869,
 47401874,
 80968732,
 744060250,
 127049276,
 324062232,
 205125399,
 427693365,
 360972139,
 168195778,
 913496573,
 299977840,
 183199642,
 416018485,
 264542552,
 78461361,
 329002439,
 108136164,
 75123404]

In [30]:
# documents = list(top_50_items_SM_df['name'])
documents = list(analyzed_df['name'])
# stopwords = ['nam', 'áo', 'quần', 'vải']
stopwords = None
Word, Count = tokenize_k_word(documents, 2, stopwords)
infor_2w_df = pd.DataFrame({'Word': Word, 'Count': Count})
infor_best_2w_df = infor_2w_df.sort_values(by='Count',ascending=False)[:1000]
infor_best_2w_df.reset_index(drop=True, inplace=True)
infor_best_2w_df

            Word  Count
0     thời trang   2149
1          sơ mi   1560
2          áo sơ   1520
3        cao cấp   1427
4         có sẵn   1186
..           ...    ...
995  coolmate cw     18
996       hở vai     18
997       nữ đen     18
998       mềm co     18
999    kong thời     18

[1000 rows x 2 columns]

In [31]:
top_shopee_mall_id = list(map(str, top_shopee_mall_id))
normal_shop_id = list(map(str, normal_shop_id))
list_total_sold = []
list_rating_average = []
list_arevenue = []
list_n_shop_mall = []
list_sm_ra = []
list_sm_sold = []
list_sm_arevenue = []
list_n_normal_shop = []
list_ns_ra = []
list_ns_sold = []
list_ns_arevenue = []
for keyword in infor_best_2w_df['Word']: 
    # Kiểm tra xem các giá trị trong cột 'Column' có chứa chuỗi cụ thể hay không
    contains_search_string = analyzed_df['name'].str.lower().str.contains(keyword)
    total_sold = analyzed_df[contains_search_string]['sold'].sum()
    list_total_sold.append(total_sold)
    rating_average = analyzed_df[contains_search_string]['rating_star'].mean()
    list_rating_average.append(rating_average)
    arevenue = analyzed_df[contains_search_string]['approximate_revenue'].sum()
    list_arevenue.append(arevenue)
    # SM
    n_shop_mall = analyzed_df[contains_search_string]['shopid'].isin(top_shopee_mall_id).sum()
    list_n_shop_mall.append(n_shop_mall)
    sm_ra = analyzed_df[contains_search_string & analyzed_df['shopid'].isin(top_shopee_mall_id)]['rating_star'].mean()
    list_sm_ra.append(sm_ra)
    sm_sold = analyzed_df[contains_search_string & analyzed_df['shopid'].isin(top_shopee_mall_id)]['sold'].sum()
    list_sm_sold.append(sm_sold)
    sm_arevenue = analyzed_df[contains_search_string & analyzed_df['shopid'].isin(top_shopee_mall_id)]['approximate_revenue'].sum()
    list_sm_arevenue.append(sm_arevenue)
    # NS
    n_normal_shop = analyzed_df[contains_search_string]['shopid'].isin(normal_shop_id).sum()
    list_n_normal_shop.append(n_normal_shop)
    ns_ra = analyzed_df[contains_search_string & analyzed_df['shopid'].isin(normal_shop_id)]['rating_star'].mean()
    list_ns_ra.append(ns_ra)
    ns_sold = analyzed_df[contains_search_string & analyzed_df['shopid'].isin(normal_shop_id)]['sold'].sum()
    list_ns_sold.append(ns_sold)
    ns_arevenue = analyzed_df[contains_search_string & analyzed_df['shopid'].isin(normal_shop_id)]['approximate_revenue'].sum()
    list_ns_arevenue.append(ns_arevenue)

In [32]:
# infor_popular_best_2w_df = infor_best_2w_df.copy()
# infor_popular_best_2w_df['Sold'] = list_sold
# infor_popular_best_2w_df['Rating_Average'] = list_rating_average
# infor_popular_best_2w_df['Shopee_Mall'] = list_shop_mall
# infor_popular_best_2w_df['Normal_Shop'] = list_normal_shop
# infor_popular_best_2w_df.sort_values(by='Sold',ascending=False)
infor_2w_df = infor_best_2w_df.copy()
infor_2w_df['Total Sold'] = list_total_sold
infor_2w_df['Approximate Revenue'] = list_arevenue
infor_2w_df['Rating Average'] = list_rating_average
infor_2w_df['Shopee Mall'] = list_n_shop_mall
infor_2w_df['SM Rating Average'] = list_sm_ra
infor_2w_df['SM Approximate Revenue'] = list_sm_arevenue
infor_2w_df['SM Sold'] = list_sm_sold
infor_2w_df['Normal Shop'] = list_n_normal_shop
infor_2w_df['NS Rating Average'] = list_ns_ra
infor_2w_df['NS Approximate Revenue'] = list_ns_arevenue
infor_2w_df['NS Sold'] = list_ns_sold
infor_2w_df['Count'] = infor_2w_df['Shopee Mall'] + infor_2w_df['Normal Shop']

In [33]:
infor_2w_df = infor_2w_df[infor_2w_df['Count'] != 0]

In [34]:
len(infor_2w_df)

963

In [35]:
infor_2w_df.sort_values(by='Total Sold',ascending=False)[:50]
# Nhớ remove 1 vài dòng bị trùng ý nghĩa hoặc không cần thiết trong top 50:
# Thương hiệu
top_50_infor_2w_df = infor_2w_df.sort_values(by='Total Sold',ascending=False)[:50]

In [36]:
infor_2w_df.to_csv('Infor_2w.csv',index=False,header=True,encoding="utf-8-sig")

In [48]:
infor_2w_df.sort_values(by='Total Sold',ascending=False)[:50]

,Word,Count,Total Sold,Approximate Revenue,Rating Average,Shopee Mall,SM Rating Average,SM Approximate Revenue,SM Sold,Normal Shop,NS Rating Average,NS Approximate Revenue,NS Sold
10,thể thao,781,71693,1.063720e+10,3.218890,427,4.730099,1.060909e+10,71566,354,1.396048,28111396.0,127
7,áo thun,1080,55001,1.040989e+10,2.830609,588,4.609981,1.040126e+10,54970,492,0.704042,8624463.0,31
23,thương hiệu,540,47412,9.494860e+09,4.117166,380,4.683213,9.490071e+09,47328,160,2.772804,4788400.0,84
48,hiệu coolmate,322,43113,9.031805e+09,4.655202,322,4.655202,9.031805e+09,43113,0,NaN,0.0,0
14,co giãn,701,42800,6.280394e+09,4.008098,423,4.583273,6.265684e+09,42601,278,3.132922,14710043.0,199
56,thao nam,281,37376,6.395445e+09,4.067457,200,4.828115,6.383371e+09,37315,81,2.189289,12073807.0,61
3,cao cấp,1416,35579,6.607730e+09,2.832964,500,4.518186,6.410606e+09,34815,916,1.913083,197124724.0,764
57,thoải mái,281,33451,5.007692e+09,4.309984,230,4.580698,5.005186e+09,33423,51,3.089119,2505894.0,28
0,thời trang,2121,32098,4.290857e+09,1.511215,523,4.599648,4.230485e+09,31823,1598,0.500420,60371632.0,275
20,áo polo,548,31715,6.513495e+09,3.904995,442,4.557154,6.512171e+09,31709,106,1.185613,1324616.0,6
32,trẻ trung,450,29774,5.744629e+09,3.522422,315,4.453061,5.737637e+09,29755,135,1.350931,6991571.0,19
159,kháng khuẩn,113,28601,2.702846e+09,4.531792,107,4.619244,2.702764e+09,28600,6,2.972222,82080.0,1
58,quần lót,272,28103,5.022340e+09,4.439552,138,4.777804,5.017551e+09,27993,134,4.091203,4788382.0,110
45,polo nam,335,24501,4.503723e+09,4.266257,271,4.684918,4.497533e+09,24484,64,2.493490,6190000.0,17
61,chất vải,278,24378,2.518770e+09,4.329045,77,4.656172,2.491574e+09,24192,201,4.203728,27196042.0,186
125,cá sấu,135,23905,3.584032e+09,4.180075,115,4.778240,3.584032e+09,23905,20,0.740625,0.0,0
52,thoáng khí,317,22855,3.262564e+09,3.486427,194,4.712332,3.257747e+09,22757,123,1.552884,4816604.0,98
182,nam guzado,99,22092,2.175823e+09,4.652687,99,4.652687,2.175823e+09,22092,0,NaN,0.0,0
13,dài tay,724,21489,5.025779e+09,3.696865,537,4.381065,5.004420e+09,21408,187,1.732076,21358529.0,81
127,vận động,131,21146,2.572029e+09,4.599930,89,4.618579,2.570193e+09,21091,42,4.560412,1836313.0,55
44,thun nam,341,20964,2.571628e+09,3.616962,247,4.580203,2.570842e+09,20958,94,1.085891,786000.0,6
402,chất nỉ,45,18001,3.651606e+09,4.622446,43,4.622973,3.651606e+09,18001,2,4.611111,0.0,0
92,lót nam,178,17432,3.091190e+09,4.073644,105,4.604645,3.087867e+09,17378,73,3.309877,3322316.0,54
233,nam thể,76,17026,1.942729e+09,4.734690,68,4.787330,1.940041e+09,17008,8,4.287250,2688000.0,18
72,mềm mại,244,16644,2.244858e+09,4.182592,222,4.427353,2.244200e+09,16640,22,1.712727,658063.0,4
390,động thoải,47,16459,1.914888e+09,4.884485,47,4.884485,1.914888e+09,16459,0,NaN,0.0,0
86,năng động,201,16330,2.934472e+09,2.556074,102,4.636479,2.933007e+09,16324,99,0.412626,1465598.0,6
55,nam cổ,299,15682,1.829642e+09,3.719692,200,4.654938,1.816568e+09,15633,99,1.830307,13074000.0,49
243,bộ thể,73,15616,3.381377e+09,4.094053,49,4.805371,3.380343e+09,15613,24,2.641778,1034000.0,3
409,cạp chun,45,15439,2.033044e+09,4.879534,42,4.887596,2.032288e+09,15435,3,4.766667,756000.0,4
156,thun levents,114,14947,5.046151e+09,4.802377,114,4.802377,5.046151e+09,14947,0,NaN,0.0,0
60,thấm hút,279,14701,2.067993e+09,4.619173,172,4.716010,2.064335e+09,14635,107,4.463510,3658199.0,66
223,nam chất,62,14663,2.989216e+09,4.246235,34,4.688203,2.972324e+09,14624,28,3.709560,16891000.0,39
875,tất nam,21,14411,3.218460e+08,4.378788,17,4.320071,3.214410e+08,14408,4,4.628333,405000.0,3
77,mềm mịn,225,14377,1.868181e+09,4.239622,195,4.389853,1.844489e+09,14244,30,3.263119,23691300.0,133
175,quần đùi,102,14098,1.416532e+09,4.658643,93,4.789853,1.415666e+09,14088,9,3.302802,865989.0,10
422,đôi tất,43,14087,5.402882e+08,3.953113,31,4.410769,5.400410e+08,14082,12,2.770833,247200.0,5
263,vải gió,70,13764,1.656148e+09,4.181134,55,4.603972,1.648657e+09,13724,15,2.630727,7491000.0,40
147,5s fashion,117,13099,2.583420e+09,4.680647,117,4.680647,2.583420e+09,13099,0,NaN,0.0,0
9,áo khoác,805,13071,3.569927e+09,2.311608,268,4.191883,3.438588e+09,12589,537,1.373221,131338160.0,482
49,dày dặn,322,13048,2.706289e+09,2.990055,181,4.408920,2.694983e+09,13014,141,1.168676,11306253.0,34
43,thiết kế,337,13017,2.807021e+09,3.847642,266,4.663881,2.806500e+09,13015,71,0.789622,521064.0,2
74,đùi nam,187,12526,1.167316e+09,4.775432,69,4.757624,1.163595e+09,12390,118,4.785845,3721093.0,136
65,sang trọng,269,12226,3.388885e+09,3.442073,182,4.396589,3.372687e+09,12177,87,1.445268,16197598.0,49
54,nam nữ,309,12100,1.610036e+09,3.369166,206,4.235247,1.605829e+09,12062,103,1.637004,4206578.0,38
12,hàn quốc,788,12067,1.590278e+09,2.463674,317,4.547781,1.563235e+09,11961,471,1.060995,27043097.0,106
19,quần short,642,11843,2.040216e+09,2.174443,241,4.458084,2.031574e+09,11803,401,0.801981,8642132.0,40
867,viền tay,21,11689,9.406160e+08,3.241890,14,4.862835,9.406160e+08,11689,7,0.000000,0.0,0
98,thanh lịch,169,11669,3.300026e+09,4.206649,156,4.285836,3.295488e+09,11666,13,3.256410,4538000.0,3
222,nam tính,79,11063,3.071066e+09,4.476194,71,4.854142,3.070822e+09,11062,8,1.121904,244500.0,1

In [37]:
top_keyword = list(top_50_infor_2w_df['Word'])

In [38]:
shop_infor_df = pd.read_csv("Malls_Information.csv",encoding="utf-8-sig")
shop_infor_df = shop_infor_df[['shopid','name']]
shop_infor_df

       shopid                            name
0    40342563                 Aviano Menswear
1   225909574                       POLOMANOR
2    68613764  TSLA Store Quần áo legging nam
3    24710134       Coolmate - Official Store
4   127217331             5S FASHION OFFICIAL
5    60297616                           ROUGH
6   111639450                         Pattern
7   317477677                     Levents .vn
8   201774917                 Guzado Official
9    59596762                Thời Trang MANDO
10  168678363                TSIMPLE_OFFICIAL
11   92937520             Thời trang nam Owen
12   68988783               Biluxury Official
13  263713672             FEAER STORE PREMIUM
14   38038824           SUKIYA OFFICIAL STORE
15  277366270                   4MEN OFFICIAL
16   70677296                BAO DANG fashion
17    1620236                         4U SHOP
18   17893078             THỜI TRANG EVEREST
19   31522834                 Kojiba Việt Nam
20   16649961  HARAS VietNam - Official Store
21  296132807              SAIGONESE.Clothing
22  257412160                           AREMI

In [39]:
len(shop_infor_df)

23

In [40]:
list_shop_name = []
list_item_name = []
list_keyword = []
list_sold = []
list_rating = []
list_arevenue = []

In [41]:
for keyword in top_keyword[:10]:
    for i in range(0,len(shop_infor_df)):
        temp_df = analyzed_df[analyzed_df['shopid'] == str(shop_infor_df['shopid'][i])]
        contains_search_string = temp_df['name'].str.lower().str.contains(keyword)
        
        for item_name in temp_df[contains_search_string]['name']:
            list_shop_name.append(shop_infor_df['name'][i])
            list_item_name.append(item_name)
            list_keyword.append(keyword)
            list_sold.append(temp_df[contains_search_string & (temp_df['name'] == item_name)]['sold'].values[0])
            list_rating.append(temp_df[contains_search_string & (temp_df['name'] == item_name)]['rating_star'].values[0])
            arevenue = temp_df[contains_search_string & (temp_df['name'] == item_name)]['sold'].values[0] * \
            temp_df[contains_search_string & (temp_df['name'] == item_name)]['price'].values[0]
            list_arevenue.append(arevenue)

In [42]:
SM_Keyword_df = pd.DataFrame({'shop_name': list_shop_name, 'item_name':list_item_name, 'keyword': list_keyword,\
                               'sold': list_sold, 'rating': list_rating, 'approximate revenue': list_arevenue})

In [43]:
SM_Keyword_df.to_csv('SM_Keyword.csv',index=False,header=True,encoding="utf-8-sig")

In [44]:
list_sm_name = []
list_sm_total_sold = []
list_sm_rating = []
list_sm_arevenue = []
for i in range(0,len(shop_infor_df)):
    temp_df = analyzed_df[analyzed_df['shopid'] == str(shop_infor_df['shopid'][i])]
    sm_name = shop_infor_df['name'][i]
    list_sm_name.append(sm_name)
    total_sold = temp_df.groupby(by=['shopid'])['sold'].sum().values[0]
    list_sm_total_sold.append(total_sold)
    rating_average = temp_df.groupby(by = ['shopid'])['rating_star'].mean().values[0]
    list_sm_rating.append(rating_average)
    arevenue = temp_df.groupby(by = ['shopid'])['approximate_revenue'].sum().values[0]
    list_sm_arevenue.append(arevenue)

In [45]:
SM_Infor_df = pd.DataFrame({'SM_Name': list_sm_name, 'SM_Total_Sold': list_sm_total_sold, \
                            'SM_Rating_Average': list_sm_rating, 'SM_Approximate_Revenue': list_sm_arevenue})
SM_Infor_df

,SM_Name,SM_Total_Sold,SM_Rating_Average,SM_Approximate_Revenue
0,Aviano Menswear,32564,4.868854,5.567569e+09
1,POLOMANOR,15959,4.843272,4.110210e+09
2,TSLA Store Quần áo legging nam,2361,4.670614,3.679548e+08
3,Coolmate - Official Store,72927,4.707948,1.356044e+10
4,5S FASHION OFFICIAL,14083,4.789382,2.848612e+09
5,ROUGH,9333,4.558269,1.196077e+09
6,Pattern,5745,4.780964,1.010936e+09
7,Levents .vn,22354,4.607361,8.519942e+09
8,Guzado Official,36727,4.770072,3.922139e+09
9,Thời Trang MANDO,1564,4.761730,3.019890e+08
10,TSIMPLE_OFFICIAL,3811,4.591569,4.369460e+08
11,Thời trang nam Owen,3441,4.143723,1.806392e+09
12,Biluxury Official,4146,4.157910,1.311942e+09
13,FEAER STORE PREMIUM,4171,4.648271,1.072975e+09
14,SUKIYA OFFICIAL STORE,11240,4.462829,1.847134e+09
15,4MEN OFFICIAL,1833,3.918238,3.655540e+08
16,BAO DANG fashion,4014,3.801418,4.108930e+08
17,4U SHOP,1367,4.370863,2.201030e+08
18,THỜI TRANG EVEREST,21764,4.831119,1.287075e+09
19,Kojiba Việt Nam,550,4.671059,6.712200e+07
20,HARAS VietNam - Official Store,5628,4.370803,5.719080e+08
21,SAIGONESE.Clothing,10261,4.509603,1.655130e+09
22,AREMI,2453,4.377508,4.024540e+08

In [46]:
SM_Infor_df.to_csv('SM_Infor.csv',index=False,header=True,encoding="utf-8-sig")